### PR TITLE
Multi-GPU (nn.DataParallel) for onmt3

### PR DESCRIPTION
**Pull request by bmccann**
This PR uses nn.DataParallel for the generator and the model. While it does seem to train correctly, additional GPUs appear to slow down the training -- currently looking into what the bottlenecks are for using nn.DataParallel for RNNs and have shared profiling info with the PyTorch team.

### CODE REVIEW

**Comment by adamlerer** [comment]
I'm looking forward to taking a look. Can you rebase your changes on top of master? I can't tell what you've done.

**Comment by bmccann** [comment]
Okay, should be good to go now. Let me know if you need anything else changed. 

I also just pushed a commit regarding loading from a checkpoint. I don't think the params should be reinitialized if train_from is set.

Even with that change though, I'm seeing something a little odd. If I load a checkpoint like model_testing_e15_1238.25.pt and skip the trainEpoch and go straight to dev, I would expect to see a validation perplexity of 1238.25 again, but instead I see ~1273. Similarly a model with validation ppl of ~10 jumping up to ~50 upon loading. (FIXED: https://github.com/adamlerer/examples/pull/2)

**Comment by bmccann** [comment]
Oh, and I forgot to mention a few things:

- Lots of transposes in here. We might be able to get rid of them, but I'll need to take another look.
- This PR depends on the recently merged https://github.com/pytorch/pytorch/pull/660. I don't think it will run with nn.DataParallel without that.
- I still haven't been able to get rid of whatever the bottleneck is that prevents nn.DataParallel from actually improving efficiency.

**Comment by adamlerer** [comment]
@bmccann sorry but this got merged into https://github.com/pytorch/examples, can you open a PR there?

**Pull request closed without merging**
